### ISSUE TITLE
This is a test

### ISSUE THREAD

**Issue by MC-Eukaryota** [JIRIPutThingsTogether/Secure-communication-handbook#1]
I read some security stuff. Here is the information I extracted:
TL;DR
**ToR is cool.**

Understanding: 7/10

**Comment by JIRIPutThingsTogether** [comment]
Thanks for that. This is my response.

**Comment by MC-Eukaryota** [comment]
- [x]  Ok

**Comment by JIRIPutThingsTogether** [comment]
I'm adding your stuff into the main stuff.
